AtmMVC/Models/ErrorViewModel.cs
namespace AtmMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AtmMVC/Models/ShowInformationViewModel.cs
using App.Domain.Core.Atm.Card.Entities;

namespace Quiz2.Endpoints.MVC.Models
{
    public class ShowInformationViewModel
    {
        public string SourceCardNumber { get; set; }
        public Card DestinationsCard { get; set; }
        public float Amount { get; set; }
        public string CodeVerify { get; set; }
    }
}

AtmMVC/Controllers/CardController.cs
using App.Domain.AppService.Atm.Card;
using App.Domain.Core.Atm.Card.AppService;
using App.Domain.Core.Atm.Card.Entities;

using Microsoft.AspNetCore.Mvc;

namespace Quiz2.Endpoints.MVC.Controllers
{
    public class CardController : Controller
    {
        private readonly ICardAppService _cardAppService;

        public CardController(ICardAppService cardAppService)
        {
            _cardAppService = cardAppService;
        }
        public IActionResult Index()
        {
                return View();
        }
       

        public IActionResult GetBalance(string cardNumber)
        {     
                var balance = _cardAppService.GetCardBalance(cardNumber);
                return View(balance);

        }


        public IActionResult Login()
        {
            return View();
        }

        public IActionResult LoginCard(string cardNumber, string password)
        {
            _cardAppService.PasswordIsValid(cardNumber, password);
            return RedirectToAction("Index", "Home");
        }
     

        public IActionResult ChangePasswordCard(string cardNumber ,string password , string newPassword)
        {
                _cardAppService.ChangePassword(cardNumber , password , newPassword);
                return RedirectToAction("Index", "Home");
        }

    }
}

AtmMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using AtmMVC;
using System.Diagnostics;
using AtmMVC.Models;

namespace Quiz2.Endpoints.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AtmMVC/Controllers/TransactionController.cs
using App.Domain.AppService.Atm.Card;

using App.Domain.AppService.Atm.Transaction;
using App.Domain.Core.Atm.Card.AppService;
using App.Domain.Core.Atm.Transaction.AppService;
using App.infra.DB.SQLServer;
using Microsoft.AspNetCore.Mvc;


namespace Quiz2.Endpoints.MVC.Controllers
{
    public class TransactionController : Controller
    {

        private readonly ITransactionAppService _transactionAppService;
        private readonly ICardAppService _cardAppService;

        public IActionResult Index()
        {
            return View();
        }
    }
}
       

AtmMVC/Views/Card/ChangePassword.cshtml
@using App.Domain.Core.Atm.Card.Entities
@model Card


<div class="container px-5 my-5">
	<form method="post" asp-action="ChangePasswordCard">



		<div class="form-floating mb-3">
			<input class=" form-control" name="password" type="text" placeholder="Password" data-sb-validations="required" value="@Model.Password" />
			<label for="password">Password</label>

		</div>
		<div class="d-grid">
			<button class="btn btn-primary btn-lg" id="submitButton" type="submit">Submit</button>

		</div>


	</form>





</div>

AtmMVC/Views/Card/GetBalance.cshtml
<div class="container px-5 my-5">
    <form>



        <div class="form-floating mb-3">
            <input disabled class=" form-control" name="Balance" type="text" placeholder="Balance" value="@Model" />
            <label for="Balance">Balance</label>

        </div>



    </form>





</div>

AtmMVC/Views/Card/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="container px-5 my-5">
   
        <div class="form-floating mb-3">
        <a asp-controller="Card" asp-action="GetBalance" class="btn btn-primary" type="button">Get Balance</a>
        </div>
    <div class="form-floating mb-3">
        <a asp-controller="Card" asp-action="ChangePassword" class="btn btn-primary" type="button">ChangePassword</a>
    </div>
        </div>

AtmMVC/Views/Card/Login.cshtml
<div class="container px-5 my-5">
    <p style="text-align:center; color:blueviolet; font-size:20px; margin-bottom:80px;">Login</p>


    <form method="post" asp-action="LoginCard">
        <div class="form-floating mb-3">
            <input class=" form-control" name="cardNumber" type="text" placeholder="Card Number" data-sb-validations="required" />
            <label for="cardNumber">Card Number</label>
        </div>
        <div class="form-floating mb-3">
            <input class=" form-control" name="password" type="text" placeholder="Password" data-sb-validations="required" />
            <label for="password">Password</label>

        </div>
        <div class="d-grid mb-3">
            <button class="btn btn-primary btn-lg" id="submitButton" type="submit">Submit</button>
        </div>

    </form>

    </div>

AtmMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AtmMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Quiz2.Endpoints.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Quiz2.Endpoints.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Quiz2.Endpoints.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="ShowTransaction">Tranaction</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Card" asp-action="Index">Card</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Transfer">Transfer Money</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Card" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AtmMVC/Views/Transaction/GenerateCode.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

AtmMVC/Views/Transaction/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<body>

    <div class="form-container">
        <h1>Transfer</h1>
        <form>
            <label for="Source-card">Source card :</label>
            <input type="text" id="Source-card" name="Source-card" required placeholder="Enter your Card Number">

            <hr>

            <label for="Destination-card">Destionation card :</label>
            <input type="text" id="Destination-card" name="Destination-card" required placeholder="Enter Destination card number">

            <hr>

            <label for="Amount">Amount :</label>
            <input type="number" id="Amount" name="Amount" required placeholder="Enter Amount to Transfer">

            <div class="button">
                <button type="submit" asp-controller="Transaction" asp-action="TransferMoney">submit  </button>
                <button type="reset">Decline</button>
            </div>
        </form>


    </div>

</body>

AtmMVC/Views/Transaction/ShowTransaction.cshtml
@using App.Domain.Core.Atm.Transaction.Dtos

@model List<TransactionDto>

<div class="table-responsive">
    <table class="table table-striped table-hover table-bordered table-sm">
        <thead>
            <tr>
               
                <th scope="col">Source Card Number</th>
                <th scope="col">Destinations Card Number</th>
                <th scope="col">TransavtionDate</th>
                <th scope="col">Amount</th>
                <th scope="col">IsSuccess</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var transaction in @Model)
            {
                <tr>
                    <th scope="row">@transaction.SourceCardNumber</th>
                    <td>@transaction.DestinationsCardNumber</td>
                    <td>@transaction.TransavtionDate</td>
                    <td>@transaction.Amount</td>
                    <td>@transaction.IsSuccess</td>
                </tr>
            }
        </tbody>
    </table>
</div>

AtmMVC/Views/Transaction/Transfer.cshtml
@model App.Domain.Core.Atm.Card.Entities.Card

<p style="text-align:center; font-size:24px;" class="mb-3">Transfer Money</p>

<div class="container px-5 my-5">
    <form method="post" asp-action="DisplayInformationTransfer">
        <div class="form-floating mb-3">
            <input disabled value=@Model.CardNumber class=" form-control" maxlength="16" name="sourceCardNumber" type="number" placeholder="Source Card Number" data-sb-validations="required" />
            <label for="sourceCardNumber">Source Card Number</label>
        </div>

        <div class="form-floating mb-3">
            <input class=" form-control" maxlength="16" name="destinationCardNumber" type="number" placeholder="Destination Card Number" data-sb-validations="required" />
            <label for="destinationCardNumber">Destination Card Number</label>
        </div>

        <div class="form-floating mb-3">
            <input class=" form-control" name="amount" type="number" placeholder="Amount" data-sb-validations="required" />
            <label for="amount">Amount</label>
        </div>
       
        <div class="d-grid">
            <button class="btn btn-primary btn-lg" id="submitButton" type="submit">Submit</button>

        </div>

    </form>
</div>